### PR TITLE
Add update endpoint method

### PR DESCRIPTION
**Pull request by zacho112**
Added update endpoint method.

But for some reason ISE won't allow to change the `name` of an ERSEndpoint, but I left it in the update method, just as it's in the add method.

Tested on ISE:

Version: 2.6.0.156
Installed Patches: 5,7

### CODE REVIEW

**Comment by falkowich** [comment]
I will check this out as soon as #164 is done

**Comment by falkowich** [comment]
Hi,

I have manually implemented the changes since i made the namechange first.. (smart move by me...)  
Here in this branch » https://github.com/falkowich/pyise-ers/tree/zacho112-pr  

But I wonder if this is by default, or this is a bug?
When you do an update on an endpoint, are we still requiring both mac and group_id?

Thougts?
--
Regards Falk

**Comment by ChilloManiac** [comment]
Bump

**Comment by falkowich** [comment]
Any more information on this, I'm trying to clean up some PR's before 0.3.
So if someone have more information on this I'm all ears :)

**Comment by falkowich** [comment]
Closing this. 
If it's still up for merge, please renew the PR.

Really sorry for the trouble.

**Pull request closed without merging**
