### PR TITLE
Add Ability to Set Custom ERS Port

### PR DESCRIPTION
**Pull request by sweickge**
Revision 1:

Added ability to set the custom port in the test files

Original submission:

Problem:

On the ISE 3.1 API Settings Overview webpage to enable the ERS API it says:

"You can manage Cisco ISE nodes through two sets of API formats—External Restful Services (ERS) and OpenAPI. Starting Cisco ISE Release 3.1, new APIs are available in the OpenAPI format.
The ERS and OpenAPI services are HTTPS-only REST APIs that operate over port 443.
Currently, ERS APIs also operate over port 9060. However, port 9060 might not be supported for ERS APIs in later Cisco ISE releases. We recommend that you only use port 443 for ERS APIs."

Right now the ERS() api object is hardcoded to use port 9060 for the ERS API, so if port 9060 is disabled in the future, the ERS() object will not work anymore.

Solution:

This pull request add the ability for a user to be able to select a different port when creating an ERS() API object, such as port 443, by using a new parameter called 'ers_port'. The default is set to port '9060' which means it should not break any existing code.

### CODE REVIEW

**Comment by falkowich** [comment]
Hi, 

Thanks for the PR!
Installing a 3.1 now, and checking out the new(ish) OpenAPI :)

I have pulled the request and done a "pytest" for backward compability, and everything seems great :)
Now I shall only try out the OpenAPI and 443.

--
Kind Regards Falk

**Comment by falkowich** [comment]
I am having problems to get a new 3.1 env running for some time, so if anyone can make some tests with this on a 3.1+ we could merge this.

I can't see any problems with the code, but can't test it out fully for the moment.

--
Kind Regards Falk

**Comment by sweickge** [comment]
@falkowich I went and made some change to my merge request to run the tests you were asking for. I added the ability to be able to use the custom port into the test files.

I ran the manual test twice. Once using the default 9060 port and a second time using the 443 port.

Here are the results:

```
$ python manual_test_ers.py 
Testing ISE 3.1 node: 10.224.0.43 using ers port 9060
add_endpoint » OK
get_endpoints » OK
get_endpoint » OK
delete_endpoint » OK
update_endpoint_group » OK
add_endpoint_group » OK
get_endpoint_groups » OK
get_endpoint_group » OK
delete_endpoint_group » OK
get_identity_groups » OK
get_identity_group » OK
add_user » OK
get_users » OK
get_user » OK
get_user_by_email » OK
delete_user » OK
get_admin_user » OK
add_device_group » OK
get_device_groups » OK
get_device_groups_from_filter » OK
get_device_group_from_name » OK
get_device_group » OK
update_device_group » OK
delete_device_group » OK
add_device » OK
add_device_multi_ip » OK
get_devices » OK
get_device » OK
delete_device » OK
add_device_payload » OK
get_device » OK
update_device » OK
update_device_radius_key » OK
get_device » OK
delete_updated_device » OK
get_sgts » OK
get_sgt » OK
add_sgt » OK
update_sgt » OK
delete_sgt » OK
get_sgacls » OK
get_sgacl » OK
add_sgacl » OK
update_sgacl » OK
delete_sgacl » OK
get_egressmatrixcells » OK
get_egressmatrixcell » OK
add_egressmatrixcell » OK
update_egressmatrixcell » OK
delete_egressmatrixcell » OK

$ python manual_test_ers.py 
Testing ISE 3.1 node: 10.224.0.43 using ers port 443
add_endpoint » OK
get_endpoints » OK
get_endpoint » OK
delete_endpoint » OK
update_endpoint_group » OK
add_endpoint_group » OK
get_endpoint_groups » OK
get_endpoint_group » OK
delete_endpoint_group » OK
get_identity_groups » OK
get_identity_group » OK
add_user » OK
get_users » OK
get_user » OK
get_user_by_email » OK
delete_user » OK
get_admin_user » OK
add_device_group » OK
get_device_groups » OK
get_device_groups_from_filter » OK
get_device_group_from_name » OK
get_device_group » OK
update_device_group » OK
delete_device_group » OK
add_device » OK
add_device_multi_ip » OK
get_devices » OK
get_device » OK
delete_device » OK
add_device_payload » OK
get_device » OK
update_device » OK
update_device_radius_key » OK
get_device » OK
delete_updated_device » OK
get_sgts » OK
get_sgt » OK
add_sgt » OK
update_sgt » OK
delete_sgt » OK
get_sgacls » OK
get_sgacl » OK
add_sgacl » OK
update_sgacl » OK
delete_sgacl » OK
get_egressmatrixcells » OK
get_egressmatrixcell » OK
add_egressmatrixcell » OK
update_egressmatrixcell » OK
delete_egressmatrixcell » OK
```

I also attempted to run the pytest tests but ran into an issue which was the issue you had reported a number of months back: https://community.cisco.com/t5/network-access-control/ise-3-1-ers-delete-ers-config-sgacl-500-internal-server-error/td-p/4829897 

Would this be enough for you to consider this tested and able to be merged?

**Review by falkowich — APPROVED** [review]

**Comment by falkowich** [comment]
A big thanks for the PR!

--
Kind Regards Falk

**Pull request merged**
